# Reusable workflow to set various useful variables
# and to perform checks and generate conditions for other workflows.
# Currently it checks if any Rust (build-related) file is changed
# and if the current (caller) workflow file is changed.
# Example:
#
# jobs:
#   preflight:
#     uses: ./.github/workflows/reusable-preflight.yml
#   some-job:
#     needs: changes
#     if: ${{ needs.preflight.outputs.changes_rust }}
#  .......

name: Preflight isdraft

on:
  workflow_call:
    # Map the workflow outputs to job outputs

jobs:
  preflight-isdraft:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'CI-Draft')
    steps:
      - name: echo test
        shell: bash
        run: echo "PR is not draft, starting CI"

